# Aim of the workshop

The general aim of the workshop is to practice the steps of the intervention mapping protocol in groups. The structure of the workshop is guided by the IM protocol, as described in the book PLANNING HEALTH PROMOTION PROGRAMS by Bartholomew et al (2016). Below, a detailed outline is presented of working with the Intervention Mapping protocol. For each step of the protocol specific tasks are formulated. 

## Oral presentations

You are performing the tasks in little groups. While working on the tasks, you make notes, and Powerpoint slides of the progress that is made by your group. You present these in the plenary sessions to receive feedback from the IM experts.

By Friday, your group will have gone through all the steps, and you will present a pptx presentation of the IM steps you have taken, ending up in your intervention, the possible ways the intervention should be designed and implemented and you provide the necessary theoretical background. You will receive expert feedback on the results of your intervention mapping and will have time to process that feedback to improve the plans. The final pptx slides must be handed in at the end of the workshop week (deadline Friday 6PM). 

## Grade

The Friday presentation will be evaluated as a group product. Team members will thus get the same grades. The presentation and final pptx slides count for 20% of your final course mark. The presentation will be evaluated by prof dr Rob Ruiter, dr GJ Peters and dr Nicole Oei. 
Submit the presentation as pdf file and send it to the following email address: N.Y.L.Oei@uva.nl.



