# Your Guest Lecturers

 	Prof Dr Rob Ruiter (MSc Health Sciences, 1995; PhD Psychology, 2000 Maastricht University) is an expert in Intervention Mapping, and coauthor of the book we use. He is a professor of applied psychology and head of department of Work and Social Psychology at the Faculty of Psychology and Neurocience, Maastricht University. The research projects he is involved in include studies into changing of risky health and safety behavior and developing and testing behavior change programs in the areas of blood donation, maternal health safe sex promotion, and traffic safety using Intervention Mapping. Since 1995, Rob is involved in PhD projects in Southern and Eastern Africa, mostly related to prevention of infectious diseases such as HIV/AIDS and malaria. These projects have the goal to develop theory- and evidence-based health education materials while training young students to become fully qualified public health researchers. See his publications [here](scholar.google.nl/citations?user=F2R3dN0AAAAJ&hl=en&oi=sra).
  We are very proud of the fact that Rob Ruiter was actively involved with this workshop from the start of the Development and Health mastertrack in 2017 With his indispensable expert knowledge in the field of Intervention Mapping. 
