project:
  type: book
  output-dir: public

book:
  title: "Intervention Mapping Work Book"
  author: "Gjalt-Jorn Peters, Nicole Oei & Rob Ruiter"
  description: >
    This is the Intervention Mapping Work Book. In the workshop/training
    that this workbook can be used for, the steps of the Intervention
    Mapping protocol are practised in groups. The structure of the workshop,
    therefore, is guided by the IM protocol. This is an Open Access book,
    freely available under the Creative Commons CC-BY-NC-SA license.
  output-file: "im-wb"
#  date: "`r format(Sys.time(), '%Y-%m-%d at %H:%M:%S (UTC%z)')`"
  date: today
  repo-url: https://gitlab.com/intervention-mapping/im-wb/
  repo-branch: master
  repo-actions: [edit, source, issue]
  downloads: [pdf, epub]
  cookie-consent: false
  url: https://im-wb.com
  chapters:
    - index.qmd
    - part: "Workbook"
      chapters:
        - step-1.qmd
        - step-2.qmd
        - step-3.qmd
        - step-4.qmd
        - step-5.qmd
    - part: "Appendices and references"
      chapters:
        - references.qmd
        - glossary.qmd

bibliography: im-wb.bib
#bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: img/im-wb-cover.png
    css: style.css
  pdf:
    documentclass: scrreprt
    cover-image: img/im-wb-cover.png
  epub:
    lang: en
    cover-image: img/im-wb-cover.png

