--- 
title: "Intervention Mapping Work Book"
author: "Nicole Oei, Gjalt-Jorn Peters & Rob Ruiter"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [im-wb.bib]
biblio-style: apalike
link-citations: yes
always_allow_html: true
description: "This is the Intervention Mapping Work Book. In the workshop/training that this workbook can be used for, the steps of the Intervention Mapping protocol are practised in groups. The structure of the workshop, therefore, is guided by the IM protocol. This is an Open Access book, freely available under the Creative Commons CC-BY-NC-SA license."
---

# Introduction {-}

Placeholder


## Aim of the workshop
### Group Work
## Core processes {#core-processes}

<!--chapter:end:index.Rmd-->

# (PART) Workbook {-}

<!--chapter:end:100---part-1---workbook.Rmd-->


# Step 1

Placeholder


## Task: Planning group
### Core Processes
### Examples
### Product
## Task: Conduct a needs assessment to create a logic model of the problem
### Core Processes
### Examples
### Product
## Task: Stating program goals 
### Core Processes
### Examples
### Product

<!--chapter:end:130---step-1.Rmd-->


# Step 2

Placeholder


## The Flip
### List target group
### Define the target behavior
### List environmental conditions
## Identify sub-behaviors/performance objectives
## Identify environmental conditions and environmental agents
## Identify environmental agent (sub-)behaviors
### Target behaviors
### Sub-behaviors / performance objectives
## Identify determinants and sub-determinants
### Long-list sub-determinants and determinants
### Select, defer, or forgo sub-determinants and determinants
## Select environmental conditions (and so, agents), and sub-behaviors and sub-determinants
## Produce Matrices of Change Objectives
## Start on the logic model of change

<!--chapter:end:140---step-2.Rmd-->


# Step 3

Placeholder


## Background information
## Select methods and applications
## Themes, components, scope and sequence

<!--chapter:end:150---step-3.Rmd-->


# Step 4

Placeholder


## Program production
## Program plan
## Program materials
## Draft messages, materials and protocols
## Pretest, refine, and produce materials. 

<!--chapter:end:160---step-4.Rmd-->

# Step 5 {#step5}

## Planning program adoption and implementation 

●	     See Chapter 8 of the book on step 5.

Step 5 is about how to implement the program: _Who has to do what to keep the program up and running_. You want the program that you have developed to be used widely, you want it to be used the way you intended it to be used and you hope it will be used for quite some time. It is therefore very important that potential program users, or implementers, are actually aware of the existence of the program, are motivated to use it, understand how to use it, etc. Consequently, you will have to repeat all the IM steps, but now aimed at the program users (who are now your target group).
So, start step 1 again, with identifying potential **adopters and implementers**. 
Then, adapt your planningsgroup (re-evaluate who should be in there), etc.


<div class="exampleList">

Example of more exercise for young children at schools:

- Who executes your programme or intervention?
  - Our intervention for young overweight children will be adopted by parents and teachers. 
- How will they know that our intervention exists?
  - Head of schools should inform them. 
  
Example for social distancing in the Kalverstraat:

- Who executes your programme or intervention?
  - The shopkeepers will adopt our intervention.
- How will they know that our intervention exists?
  - The municipality should inform them.
</div>

<!--chapter:end:170---step-5.Rmd-->

# (PART) Appendices and references {-}

<!--chapter:end:900---part---appendices-and-references.Rmd-->

# References


<!--chapter:end:999-references.Rmd-->

