author: Gjalt-Jorn Peters, Nicole Oei & Rob Ruiter, © Copyright Maastricht University <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="license noopener noreferrer">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" alt=""></a>
execute:
  execute_notebooks: "off"

html:
  use_multitoc_numbering: true

sphinx:
  extra_extensions:
    - teachbooks_favourites
  config:
    language: en
    html_favicon: "figures/TB_favicon.ico"
    html_baseurl: "https://maastrichtuniversitypress.github.io/open-up-intervention-mapping"
    html_static_path: ["figures"]
    html_theme_options:
      logo:
        text: Intervention Mapping Work Book
        image_light: im-wb-cover.png
        image_dark: im-wb-cover.png
      repository_url: "https://github.com/MaastrichtUniversityPress/open-up-intervention-mapping"
      path_to_docs: "book"
      repository_branch: "teachbook"
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button: true
    html_show_copyright: false
    external_toc_exclude_missing: true
    external_toc_path: "_toc.yml"

teachbooks:
  attribution_location: top

bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]
  myst_links_external_new_tab: true
